//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMPhanLop
{
    using System;
    using System.Collections.Generic;
    
    public partial class chiphi
    {
        public int idchiphi { get; set; }
        public Nullable<int> idloaicp { get; set; }
        public Nullable<int> iddoan { get; set; }
        public Nullable<int> tongtien { get; set; }
        public string ghichu { get; set; }
    
        public virtual doan doan { get; set; }
        public virtual loaichiphi loaichiphi { get; set; }
    }
}
