//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMPhanLop
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietdoan
    {
        public int idchitietdoan { get; set; }
        public Nullable<int> idkhach { get; set; }
        public Nullable<int> iddoan { get; set; }
    
        public virtual doan doan { get; set; }
        public virtual khach khach { get; set; }
    }
}
