//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMPhanLop
{
    using System;
    using System.Collections.Generic;
    
    public partial class diadiem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public diadiem()
        {
            this.tour_diadiem = new HashSet<tour_diadiem>();
        }
    
        public int iddiadiem { get; set; }
        public string tendiadiem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tour_diadiem> tour_diadiem { get; set; }
    }
}
