//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMPhanLop
{
    using System;
    using System.Collections.Generic;
    
    public partial class doan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doan()
        {
            this.chiphis = new HashSet<chiphi>();
            this.chitietdoans = new HashSet<chitietdoan>();
            this.phancongs = new HashSet<phancong>();
        }
    
        public int iddoan { get; set; }
        public Nullable<int> idtour { get; set; }
        public string tendoan { get; set; }
        public Nullable<System.DateTime> ngaykhoihanh { get; set; }
        public Nullable<System.DateTime> ngayketthuc { get; set; }
        public Nullable<int> tongchiphi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chiphi> chiphis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietdoan> chitietdoans { get; set; }
        public virtual tour tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phancong> phancongs { get; set; }
    }
}
