//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMPhanLop
{
    using System;
    using System.Collections.Generic;
    
    public partial class phancong
    {
        public int idphancong { get; set; }
        public Nullable<int> iddoan { get; set; }
        public Nullable<int> idnhanvien { get; set; }
        public string chucvu { get; set; }
        public string ghichu { get; set; }
    
        public virtual doan doan { get; set; }
        public virtual nhanvien nhanvien { get; set; }
    }
}
