//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMPhanLop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMPhanLopEntities : DbContext
    {
        public PMPhanLopEntities()
            : base("name=PMPhanLopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chitietdoan> chitietdoans { get; set; }
        public virtual DbSet<diadiem> diadiems { get; set; }
        public virtual DbSet<doan> doans { get; set; }
        public virtual DbSet<gia> gias { get; set; }
        public virtual DbSet<khach> khaches { get; set; }
        public virtual DbSet<loaichiphi> loaichiphis { get; set; }
        public virtual DbSet<loaidulich> loaiduliches { get; set; }
        public virtual DbSet<nhanvien> nhanviens { get; set; }
        public virtual DbSet<phancong> phancongs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tour> tours { get; set; }
        public virtual DbSet<tour_diadiem> tour_diadiem { get; set; }
        public virtual DbSet<chiphi> chiphis { get; set; }
    }
}
