//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMPhanLop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour_diadiem
    {
        public int idtour_diadiem { get; set; }
        public Nullable<int> idtour { get; set; }
        public Nullable<int> iddiadiem { get; set; }
    
        public virtual diadiem diadiem { get; set; }
        public virtual tour tour { get; set; }
    }
}
